const puzzles = [
    {
        title: "Superheroes / Villains",
        words: [
            "spiderman",
            "superman",
            "batman",
            "wolverine",
            "captainAmerica",
            "hulk",
            "ironman",
            "joker",
            "venom",
            "magneto",
            "dococt",
            "lexLuther",
            "redSkull",
        ],
    },
    {
        title: "Dinosaurs",
        words: [
            "brachiosaurus",
            "triceratops",
            "tyrannosaurusRex",
            "velociraptor",
            "pterodactyl",
            "allosaurus",
            "coelophysis",
            "stegosaurus",
            "ankylosaurus",
            "diplodocus",
            "plesiosaurus",
        ],
    },
    {
        title: "Animals",
        words: [
            "horse",
            "mouse",
            "snake",
            "bear",
            "lizard",
            "lion",
            "cow",
            "chicken",
            "pig",
            "dog",
            "kitten",
            "trout",
            "cheetah",
            "rabbit",
            "eagle",
            "duck",
            "squirrel",
        ],
    },
    {
        title: "Elements",
        words: [
            "oxygen",
            "gold",
            "krypton",
            "einsteinium",
            "helium",
            "mercury",
            "carbon",
            "hydrogen",
            "magnesium",
            "barium",
            "titanium",
            "iron",
            "copper",
            "tin",
            "zinc",
        ],
    },
    {
        title: "Crayola Colors",
        words: [
            "marigold",
            "goldenrod",
            "tumbleweed",
            "macaroniAndCheese",
            "periwinkle",
            "cornFlower",
            "springGreen",
            "salmon",
            "bluetiful",
            "wisteria",
            "robinsEggBlue",
            "melon",
            "mauvelous",
            "asparagus",
        ],
    },
    {
        title: "Fantasy",
        words: [
            "unicorn",
            "pegasus",
            "dwarf",
            "witch",
            "wizard",
            "dragon",
            "gnome",
            "princess",
            "hobbit",
            "giant",
            "moat",
            "griffin",
            "seaSnake",
            "leprechaun",
            "mermaid",
            "fairy",
            "fawn",
            "knight",
            "castle",
        ],
    },
    {
        title: "Three-letter words",
        words: [
            "dew",
            "the",
            "ant",
            "dog",
            "add",
            "bug",
            "mom",
            "dad",
            "bat",
            "leg",
            "red",
            "bad",
            "rug",
            "gum",
            "gun",
            "bye",
            "buy",
            "bog",
            "mad",
            "sad",
            "rad",
            "rag",
            "mud",
            "pea",
            "pad",
            "toe",
            "bed",
            "fog",
            "dud",
            "cup",
            "cap",
            "sip",
            "lip",
            "kit",
            "pit",
            "man",
        ],
    },
    {
        title: "Flowers",
        words: [
            "lily",
            "lavender",
            "rose",
            "orchid",
            "violet",
            "sunFlower",
            "daffodil",
            "tulip",
            "carnation",
            "forgetMeNot",
            "blueBonnet",
        ],
    },
    {
        title: "Countries",
        words: [
            "USA",
            "russia",
            "brazil",
            "peru",
            "cuba",
            "spain",
            "france",
            "greece",
            "japan",
            "china",
            "siberia",
            "iran",
            "southKorea",
            "nigeria",
            "vietnam",
            "greenland",
            "australia",
            "indonesia",
            "india",
            "botswana",
        ],
    },
    {
        title: "Fruits",
        words: [
            "apple",
            "banana",
            "orange",
            "grape",
            "blueberry",
            "jackfruit",
            "pineapple",
            "dragonFruit",
            "pomegranate",
            "peach",
            "pear",
            "cantaloupe",
            "watermelon",
        ],
    },
    {
        title: "Idaho Cities",
        words: [
            "boise",
            "eagle",
            "twinFalls",
            "mccall",
            "meridian",
            "kuna",
            "gardenCity",
            "caldwell",
            "nampa",
            "emmet",
            "idahoCity",
            "pocatello",
        ],
    },
    {
        title: "Programming Concepts",
        words: [
            "forLoop",
            "array",
            "class",
            "variable",
            "conditional",
            "chaining",
            "logicalOperator",
            "function",
            "console",
            "parameters",
            "pseudoRandom",
        ],
    },
    {
        title: "Random",
        words: [
            "siege",
            "glass",
            "backward",
            "tuxedo",
            "biography",
            "subway",
            "prisoner",
            "wordSearch",
            "basketball",
            "frisbee",
            "calculus",
            "stopSign",
            "motorcycle",
            "microwave",
            "ceilingFan",
            "paradise",
            "cheeseburger",
            "yacht",
            "coconut",
            "asylum",
            "pickle",
            "machineGun",
            "crystal",
            "purple",
            "pillow",
        ],
    },
];

export default puzzles;
